plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.75'
    id 'idea'
}

repositories {
    mavenLocal()
    maven { url = "https://cursemaven.com" }
    maven { url = "https://harleyoconnor.com/maven" }
}

base {
    archivesName = modId
}

modName = project.modName
modId = project.modId
modVersion = project.modVersion
mcVersion = project.mcVersion
AuthorName = project.AuthorName
version = modVersion


java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neoforgeVersion

    parchment {
        mappingsVersion = project.mappingsVersion
        minecraftVersion = mcVersion
    }

    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        // This run config launches GameTestServer and runs all registered gametests, then exits.
        // By default, the server will crash when no gametests are provided.
        // The gametest system is also enabled by default for other run configs under the /test command.
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', modId
        }

        data {
            data()

            // example of overriding the workingDirectory set in configureEach above, uncomment if you want to use it
            // gameDirectory = project.file('run-data')

            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', modId, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    //DynamicTrees
    //implementation(fg.deobf("com.ferreusveritas.dynamictrees:DynamicTrees-$mcVersion:${property("dynamicTreesVersion")}"))
    //runtimeOnly(fg.deobf("com.ferreusveritas.dynamictreesplus:DynamicTreesPlus-$mcVersion:${property("dynamicTreesPlusVersion")}"))
    implementation "curse.maven:dynamictrees-252818:6111832"

    //DynmaicTrees Tools/Utilities
    //runtimeOnly(fg.deobf("curse.maven:jade-324717:5072729"))
    //runtimeOnly(fg.deobf("curse.maven:jei-238222:5101366"))
    //runtimeOnly(fg.deobf("curse.maven:cc-tweaked-282001:5118388"))
    //runtimeOnly(fg.deobf("curse.maven:suggestion-provider-fix-469647:4591193"))

    //Other
    //implementation(fg.deobf("curse.maven:template-projectid:fileid"))
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : mcVersion,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neoforgeVersion,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : modId,
            mod_name               : modName,
            mod_license            : mod_license,
            mod_version            : modVersion,
            mod_authors            : AuthorName,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
