mod_name=DynamicTreesTemplate
mod_id=dttemplate
modId=dttemplate
mod_version=1.0.0
mod_group_id=group.dttemplate
mod_authors=Template

minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neo_version=21.1.97

dynamicTreesVersion=1.5.0-BETA02
dynamicTreesPlusVersion=1.2.0-BETA2

curseFileType=release

org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
