modName=DynamicTreesTemplate
modId=dttemplate
modVersion=1.0.0
group=group.dttemplate
AuthorName=Template
minecraft_version_range=[1.21.1]

mcVersion=1.21.1
neoforgeVersion=21.1.97
neo_version_range=[21.1.97,)
loader_version_range=[1,)
mappingsVersion=2024.11.17

mod_license=MIT
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.

dynamicTreesVersion=1.5.0-BETA02
dynamicTreesPlusVersion=1.2.0-BETA2

curseFileType=release

org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
