modName=DynamicTreesTemplate
modId=dttemplate
modVersion=1.0.0
group=group.dttemplate
AuthorName=Template

mcVersion=1.18.2
forgeVersion=40.2.0
mappingsVersion=2022.09.04

dynamicTreesVersion=1.0.4
dynamicTreesPlusVersion=1.0.4

curseFileType=release

org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
