license="MIT"
modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/AuthorName/DynamicTreesTemplate/issues"

[[mods]]
modId="dttemplate"
version="${file.jarVersion}"
displayName="Dynamic Trees for Template"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-template"
logoFile="logo.png"
credits=""
authors="AuthorName"
description='''
Adds Dynamic Trees compatibility for Template.
'''

[[dependencies.dttemplate]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttemplate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttemplate]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[0.10.5,)"
    ordering="AFTER"
    side="BOTH"
