modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/AuthorName/DynamicTreesTemplate/issues"

[[mods]]
modId="dttemplate"
version="${file.jarVersion}"
displayName="Dynamic Trees for Template"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-template"
logoFile="logo.png"
credits=""
authors="Template"
description='''
Adds Dynamic Trees compatibility for Template.
'''

[[dependencies.dttemplate]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttemplate]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttemplate]]
    modId="dynamictrees"
    type="required"
    versionRange="[1.5.0-BETA01,)"
    ordering="AFTER"
    side="BOTH"
