license="MIT"
modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/AuthorName/DynamicTreesTemplate/issues"

[[mods]]
modId="dttemplate"
version="1.0.0"
displayName="Dynamic Trees for Template"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-template"
logoFile="logo.png"
credits=""
authors="Template"
description='''
Adds Dynamic Trees compatibility for Template.
'''

[[dependencies.dttemplate]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttemplate]]
    modId="minecraft"
    type="required"
    versionRange="&{minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.dttemplate]]
    modId="dynamictrees"
    type="required"
    versionRange="[1.5.0-BETA01,)"
    ordering="AFTER"
    side="BOTH"
